"use client";
import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { Track } from "@/lib/quiz";

type Mode = "home" | "trackle" | "cover" | "higher" | "speed" | "rank";
const shuffle = <T,>(items: T[]) => [...items].sort(() => Math.random() - 0.5);
const choices = (tracks: Track[], target: Track) => shuffle([target.artist, ...shuffle([...new Set(tracks.map((track) => track.artist).filter((artist) => artist !== target.artist))]).slice(0, 3)]);

export default function Arcade({ tracks }: { tracks: Track[] }) {
  const [mode, setMode] = useState<Mode>("home"); const [seed, setSeed] = useState(0);
  const restart = (next: Mode) => { setSeed((value) => value + 1); setMode(next); };
  if (mode === "trackle") return <Trackle key={seed} tracks={tracks} back={() => setMode("home")} />;
  if (mode === "cover") return <CoverRush key={seed} tracks={tracks} back={() => setMode("home")} />;
  if (mode === "higher") return <HigherLower key={seed} tracks={tracks} back={() => setMode("home")} />;
  if (mode === "speed") return <SpeedRun key={seed} tracks={tracks} back={() => setMode("home")} />;
  if (mode === "rank") return <RankBattle key={seed} tracks={tracks} back={() => setMode("home")} />;
  const games: { mode: Mode; eyebrow: string; title: string; detail: string; color: string }[] = [
    { mode: "trackle", eyebrow: "Word puzzle", title: "Trackle", detail: "Find one of your top tracks in six guesses.", color: "bg-[#1ed760] text-black" },
    { mode: "cover", eyebrow: "Visual memory", title: "Cover Rush", detail: "Name the artist before the album art comes into focus.", color: "bg-fuchsia-500 text-white" },
    { mode: "higher", eyebrow: "Gut check", title: "Higher / Lower", detail: "Is the next song more or less popular on Spotify?", color: "bg-sky-500 text-black" },
    { mode: "speed", eyebrow: "30 seconds", title: "Speed Run", detail: "How many of your own artists can you identify?", color: "bg-orange-400 text-black" },
    { mode: "rank", eyebrow: "Know your taste", title: "Rank Battle", detail: "Which track ranks higher in your current top music?", color: "bg-violet-500 text-white" },
  ];
  return <div className="mx-auto max-w-6xl px-5 py-10 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#1ed760]">Five ways to play</p><h1 className="mt-3 text-5xl font-black tracking-[-.05em] sm:text-6xl">The music arcade.</h1><p className="mt-4 max-w-xl text-zinc-400">No generic trivia—every game is made from music you actually know.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{games.map((game) => <button key={game.mode} onClick={() => restart(game.mode)} className={`min-h-56 rounded-[2rem] p-7 text-left transition hover:scale-[1.02] ${game.color}`}><p className="text-xs font-black uppercase tracking-[.18em] opacity-70">{game.eyebrow}</p><h2 className="mt-10 text-4xl font-black leading-none">{game.title}</h2><p className="mt-5 max-w-xs text-sm font-bold opacity-75">{game.detail}</p><span className="mt-7 inline-block text-sm font-black">Play →</span></button>)}</div></div>;
}

const Shell = ({ title, detail, back, children }: { title: string; detail: string; back: () => void; children: ReactNode }) => <div className="mx-auto max-w-2xl px-5 py-10 text-white"><button onClick={back} className="text-sm font-bold text-[#1ed760]">← Music arcade</button><p className="mt-10 text-xs font-bold uppercase tracking-[.2em] text-[#1ed760]">{detail}</p><h1 className="mt-3 text-5xl font-black tracking-[-.05em]">{title}</h1>{children}</div>;

function Trackle({ tracks, back }: { tracks: Track[]; back: () => void }) { const target = useMemo(() => shuffle(tracks)[0], [tracks]); const [guess, setGuess] = useState(""); const [attempts, setAttempts] = useState<string[]>([]); const normalized = (value: string) => value.toUpperCase().replace(/[^A-Z0-9]/g, ""); const answer = normalized(target.name); const submit = () => { if (guess.trim() && attempts.length < 6 && !attempts.includes(guess)) setAttempts([...attempts, guess]); setGuess(""); }; const won = attempts.some((item) => normalized(item) === answer); return <Shell title="Trackle" detail={`A ${target.name.length}-character track from your top music`} back={back}><p className="mt-5 text-zinc-400">Hint: it&apos;s by <strong className="text-white">{target.artist}</strong>.</p><div className="mt-8 space-y-2">{[...attempts, ...Array(Math.max(0, 6 - attempts.length)).fill("")].map((item, row) => <div key={row} className="flex gap-1">{Array.from({ length: Math.min(answer.length, 12) }, (_, index) => { const char = normalized(item)[index]; const state = char ? char === answer[index] ? "bg-[#1ed760] text-black" : answer.includes(char) ? "bg-orange-400 text-black" : "bg-zinc-700" : "bg-white/10"; return <span key={index} className={`grid h-10 w-8 place-items-center rounded font-black sm:h-12 sm:w-10 ${state}`}>{char}</span>; })}</div>)}</div>{won || attempts.length === 6 ? <div className="mt-8 rounded-2xl bg-[#1ed760] p-5 font-black text-black">{won ? "You got it!" : `It was ${target.name}.`}</div> : <div className="mt-8 flex gap-2"><input value={guess} onChange={(event) => setGuess(event.target.value)} onKeyDown={(event) => event.key === "Enter" && submit()} placeholder="Type a track title" className="min-w-0 flex-1 rounded-full bg-white px-5 py-3 text-black outline-none" /><button onClick={submit} className="rounded-full bg-[#1ed760] px-5 font-black text-black">Guess</button></div>}</Shell>; }

function CoverRush({ tracks, back }: { tracks: Track[]; back: () => void }) { const target = useMemo(() => shuffle(tracks)[0], [tracks]); const [blur, setBlur] = useState(20); const [answer, setAnswer] = useState<string | null>(null); const options = useMemo(() => choices(tracks, target), [tracks, target]); const score = Math.max(25, 100 - (20 - blur) * 4); return <Shell title="Cover Rush" detail="Name the artist before the image resolves" back={back}><div className="mt-8 overflow-hidden rounded-[2rem] bg-zinc-800"><img src={target.albumArt} alt="Mystery album cover" className="aspect-square w-full object-cover transition duration-500" style={{ filter: `blur(${blur}px) scale(1.12)` }} /></div><p className="mt-5 text-center text-sm text-zinc-400">Potential score: <strong className="text-[#1ed760]">{score}</strong></p>{answer ? <div className={`mt-5 rounded-2xl p-5 font-black ${answer === target.artist ? "bg-[#1ed760] text-black" : "bg-red-500 text-white"}`}>{answer === target.artist ? `Correct — ${score} points!` : `Not quite. It was ${target.artist}.`}</div> : <><div className="mt-5 grid gap-2">{options.map((option) => <button key={option} onClick={() => setAnswer(option)} className="rounded-xl border border-white/10 p-4 text-left font-bold hover:bg-white/10">{option}</button>)}</div><button onClick={() => setBlur(Math.max(0, blur - 5))} className="mt-4 text-sm font-bold text-[#1ed760]">Reveal a little more (−20 points)</button></>}</Shell>; }

function HigherLower({ tracks, back }: { tracks: Track[]; back: () => void }) { const pair = useMemo(() => shuffle(tracks).slice(0, 2), [tracks]); const [result, setResult] = useState<string | null>(null); if (pair.length < 2) return null; const [left, right] = pair; const correct = right.popularity >= left.popularity ? "higher" : "lower"; return <Shell title="Higher / Lower" detail="Spotify popularity showdown" back={back}><div className="mt-8 grid gap-4 sm:grid-cols-2"><TrackTile track={left} label={`${left.popularity}/100`} /><TrackTile track={right} label="? /100" /></div>{result ? <div className={`mt-6 rounded-2xl p-5 font-black ${result === correct ? "bg-[#1ed760] text-black" : "bg-red-500"}`}>{result === correct ? "Correct." : "Wrong."} {right.name} is {right.popularity}/100.</div> : <div className="mt-6 grid grid-cols-2 gap-3"><button onClick={() => setResult("higher")} className="rounded-full bg-[#1ed760] py-3 font-black text-black">Higher</button><button onClick={() => setResult("lower")} className="rounded-full border border-white/20 py-3 font-black">Lower</button></div>}</Shell>; }
const TrackTile = ({ track, label }: { track: Track; label: string }) => <div className="overflow-hidden rounded-2xl bg-[#151515]"><img src={track.albumArt} alt="" className="aspect-square w-full object-cover" /><div className="p-4"><p className="truncate font-black">{track.name}</p><p className="truncate text-sm text-zinc-500">{track.artist}</p><p className="mt-4 text-2xl font-black text-[#1ed760]">{label}</p></div></div>;

function SpeedRun({ tracks, back }: { tracks: Track[]; back: () => void }) { const [time, setTime] = useState(30); const [score, setScore] = useState(0); const [index, setIndex] = useState(0); const sequence = useMemo(() => shuffle(tracks).slice(0, 10), [tracks]); const target = sequence[index]; const options = useMemo(() => target ? choices(tracks, target) : [], [tracks, target]); useEffect(() => { if (time <= 0 || index >= sequence.length) return; const timer = setTimeout(() => setTime(time - 1), 1000); return () => clearTimeout(timer); }, [time, index, sequence.length]); if (!target || time === 0) return <Shell title="Speed Run" detail="Time&apos;s up" back={back}><div className="mt-8 rounded-[2rem] bg-[#1ed760] p-8 text-black"><p className="text-6xl font-black">{score}</p><p className="mt-2 font-bold">artists identified in 30 seconds</p></div></Shell>; const pick = (option: string) => { if (option === target.artist) setScore(score + 1); setIndex(index + 1); }; return <Shell title="Speed Run" detail={`${time}s left · ${score} correct`} back={back}><img src={target.albumArt} alt="" className="mt-8 h-52 w-full rounded-[2rem] object-cover" /><p className="mt-6 text-2xl font-black">Who made this?</p><div className="mt-5 grid gap-2">{options.map((option) => <button key={option} onClick={() => pick(option)} className="rounded-xl border border-white/10 p-4 text-left font-bold hover:bg-white/10">{option}</button>)}</div></Shell>; }

function RankBattle({ tracks, back }: { tracks: Track[]; back: () => void }) { const pair = useMemo(() => shuffle(tracks).slice(0, 2), [tracks]); const [picked, setPicked] = useState<Track | null>(null); if (pair.length < 2) return null; const ranks = new Map(tracks.map((track, index) => [track.id, index])); const winner = (ranks.get(pair[0].id) || 0) < (ranks.get(pair[1].id) || 0) ? pair[0] : pair[1]; return <Shell title="Rank Battle" detail="Which song sits higher in your current top tracks?" back={back}><div className="mt-8 grid gap-4 sm:grid-cols-2">{pair.map((track) => <button key={track.id} onClick={() => setPicked(track)} className="overflow-hidden rounded-2xl bg-[#151515] text-left transition hover:scale-[1.02]"><img src={track.albumArt} alt="" className="aspect-square w-full object-cover" /><div className="p-5"><p className="font-black">{track.name}</p><p className="text-sm text-zinc-500">{track.artist}</p></div></button>)}</div>{picked && <div className={`mt-6 rounded-2xl p-5 font-black ${picked.id === winner.id ? "bg-[#1ed760] text-black" : "bg-red-500"}`}>{picked.id === winner.id ? "Exactly right." : `Close—${winner.name} wins this round.`}</div>}</Shell>; }
