"use client";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import { AnswerRecord, readAnswerHistory } from "@/lib/history";
import { achievementsFor, currentStreak, PlayerProgress, readPlayerProgress } from "@/lib/player";

export default function DashboardPage() {
  const { data: session, status } = useSession(); const [answers, setAnswers] = useState<AnswerRecord[]>([]); const [progress, setProgress] = useState<PlayerProgress>({ rounds: [], dailyDates: [] });
  useEffect(() => { if (status === "unauthenticated") window.location.assign("/login"); if (status === "authenticated") { const key = session.user?.email || session.user?.name || "spotify-player"; setAnswers(readAnswerHistory(key)); setProgress(readPlayerProgress(key)); } }, [status, session]);
  if (status === "loading") return <main className="grid min-h-screen place-items-center bg-[#070707]"><span className="h-9 w-9 animate-spin rounded-full border-2 border-[#1ed760] border-t-transparent" /></main>;
  if (status === "unauthenticated") return null;
  const correct = answers.filter((answer) => answer.isCorrect).length; const accuracy = answers.length ? Math.round(correct / answers.length * 100) : 0; const streak = currentStreak(progress.dailyDates); const achievements = achievementsFor(progress, correct);
  return <main className="min-h-screen bg-[#070707] px-5 text-white"><header className="mx-auto flex max-w-5xl items-center justify-between py-6"><Link href="/" className="text-lg font-black"><span className="text-[#1ed760]">spoti</span>quiz</Link><div className="flex gap-2"><Link href="/listening" className="hidden rounded-full border border-white/15 px-4 py-2 text-sm font-bold sm:block">Listening</Link><Link href="/profile" className="rounded-full border border-white/15 px-4 py-2 text-sm font-bold">Account</Link></div></header><section className="mx-auto max-w-5xl py-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#1ed760]">Your progress</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Made for your next replay.</h1><div className="mt-9 grid gap-3 sm:grid-cols-4">{[[streak, "day streak"], [progress.rounds.length, "rounds played"], [correct, "correct answers"], [`${accuracy}%`, "accuracy"]].map(([value, label]) => <div key={label as string} className="rounded-2xl border border-white/10 bg-[#151515] p-5"><p className="text-3xl font-black text-[#1ed760]">{value}</p><p className="mt-1 text-sm text-zinc-500">{label}</p></div>)}</div><div className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><section><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#1ed760]">Achievements</p><h2 className="mt-2 text-2xl font-black">Your collection</h2></div><span className="text-sm text-zinc-500">{achievements.filter((item) => item.unlocked).length}/{achievements.length}</span></div><div className="mt-5 grid gap-3">{achievements.map((achievement) => <div key={achievement.name} className={`rounded-2xl border p-5 ${achievement.unlocked ? "border-[#1ed760]/30 bg-[#1ed760]/10" : "border-white/10 bg-[#151515] opacity-55"}`}><p className="font-black">{achievement.unlocked ? "✦ " : "○ "}{achievement.name}</p><p className="mt-1 text-sm text-zinc-500">{achievement.detail}</p></div>)}</div></section><section><p className="text-xs font-bold uppercase tracking-[.18em] text-[#1ed760]">Recent rounds</p><h2 className="mt-2 text-2xl font-black">Your scorecard</h2><div className="mt-5 overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#151515]">{progress.rounds.length ? progress.rounds.slice(0, 5).map((round) => <div key={round.id} className="flex items-center justify-between border-b border-white/10 p-5 last:border-0"><div><p className="font-bold">{round.mode === "daily" ? "Daily challenge" : "Free play"}</p><p className="mt-1 text-xs text-zinc-500">{new Date(round.completedAt).toLocaleDateString()}</p></div><p className="text-xl font-black text-[#1ed760]">{round.score}/{round.total}</p></div>) : <div className="p-8 text-sm text-zinc-500">Play your first round to start your scorecard.</div>}</div><Link href="/quiz" className="mt-5 inline-block rounded-full bg-[#1ed760] px-6 py-3 text-sm font-black text-black">Play now</Link></section></div></section></main>;
}
