"use client";

import Link from "next/link";
import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";

type Track = { id: string; name: string; artist: string; albumArt: string; playedAt?: string };
type Artist = { id: string; name: string; image: string; genres: string[] };
type ListeningData = { allTimeTracks: Track[]; topArtists: Artist[]; recent: Track[]; profile: { displayName?: string; image?: string } | null };

const dateLabel = (date?: string) => date ? new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(date)) : "Recently";

export default function ListeningPage() {
  const { status } = useSession(); const [data, setData] = useState<ListeningData | null>(null); const [error, setError] = useState(false);
  useEffect(() => { if (status === "unauthenticated") window.location.assign("/login"); if (status === "authenticated") fetch("/api/spotify/top-tracks").then((response) => response.ok ? response.json() : Promise.reject()).then(setData).catch(() => setError(true)); }, [status]);
  if (status === "loading" || (status === "authenticated" && !data && !error)) return <main className="grid min-h-screen place-items-center bg-[#070707] px-5 text-white"><div className="w-full max-w-sm rounded-[2rem] border border-white/10 bg-[#151515] p-8 text-center"><span className="mx-auto block h-9 w-9 animate-spin rounded-full border-2 border-[#1ed760] border-t-transparent" /><p className="mt-6 text-xl font-black">Loading your listening profile</p><p className="mt-2 text-sm leading-relaxed text-zinc-500">We&apos;re checking your Spotify session and collecting your top music.</p><Link href="/quiz" className="mt-7 inline-block text-sm font-bold text-[#1ed760] underline">Back to quiz</Link></div></main>;
  if (status === "unauthenticated") return null;
  if (error) return <main className="grid min-h-screen place-items-center bg-[#070707] px-5 text-white"><div className="max-w-sm text-center"><p className="text-2xl font-black">Couldn&apos;t load your listening profile.</p><button className="mt-5 rounded-full bg-[#1ed760] px-5 py-3 font-bold text-black" onClick={() => location.reload()}>Try again</button></div></main>;
  const favourite = data?.allTimeTracks[0];
  return <main className="min-h-screen bg-[#070707] text-white"><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6"><Link href="/" className="text-lg font-black"><span className="text-[#1ed760]">spoti</span>quiz</Link><nav className="flex items-center gap-3"><Link href="/history" className="hidden text-sm font-bold text-zinc-400 hover:text-white sm:block">My answers</Link><Link href="/quiz" className="rounded-full bg-[#1ed760] px-4 py-2 text-sm font-black text-black">Play quiz</Link></nav></header>
    <section className="mx-auto max-w-6xl px-5 pb-16 pt-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#1ed760]">Listening profile</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">Your sound, <span className="text-[#1ed760]">unpacked.</span></h1><p className="mt-4 max-w-2xl text-zinc-400">A snapshot of your Spotify long-term favourites and most recent spins.</p>
      {favourite && <section className="mt-10 overflow-hidden rounded-[2rem] border border-[#1ed760]/25 bg-[#151515] sm:grid sm:grid-cols-[.9fr_1.1fr]"><img src={favourite.albumArt} alt="" className="h-64 w-full object-cover sm:h-full" /><div className="flex flex-col justify-between p-7 sm:p-10"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#1ed760]">Your #1 long-term track</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">{favourite.name}</h2><p className="mt-3 text-lg text-zinc-400">{favourite.artist}</p></div><p className="mt-10 text-sm leading-relaxed text-zinc-500">Based on Spotify&apos;s long-term listening affinity. Spotify does not provide precise lifetime play counts through its API.</p></div></section>}
      <div className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><section><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#1ed760]">Long-term favourites</p><h2 className="mt-2 text-2xl font-black">Top tracks</h2></div><span className="text-sm text-zinc-500">Top {data?.allTimeTracks.length || 0}</span></div><div className="mt-5 overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#151515]">{data?.allTimeTracks.map((track, index) => <div key={track.id} className="flex items-center gap-4 border-b border-white/10 p-4 last:border-0"><span className="w-5 text-center text-sm font-black text-zinc-500">{index + 1}</span><img src={track.albumArt} alt="" className="h-12 w-12 rounded-xl object-cover" /><div className="min-w-0"><p className="truncate font-bold">{track.name}</p><p className="truncate text-sm text-zinc-500">{track.artist}</p></div></div>)}</div></section>
      <section><p className="text-xs font-bold uppercase tracking-[.18em] text-[#1ed760]">Your core artists</p><h2 className="mt-2 text-2xl font-black">On repeat</h2><div className="mt-5 grid grid-cols-2 gap-3">{data?.topArtists.map((artist, index) => <div key={artist.id} className="overflow-hidden rounded-2xl border border-white/10 bg-[#151515]"><img src={artist.image} alt="" className="aspect-square w-full object-cover" /><div className="p-4"><p className="text-xs font-black text-[#1ed760]">#{index + 1}</p><p className="mt-1 truncate font-bold">{artist.name}</p><p className="mt-1 truncate text-xs text-zinc-500">{artist.genres.join(" · ") || "Top artist"}</p></div></div>)}</div></section></div>
      <section className="mt-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#1ed760]">Latest plays</p><h2 className="mt-2 text-2xl font-black">Fresh from your queue</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data?.recent.slice(0, 9).map((track) => <div key={`${track.id}-${track.playedAt}`} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-[#151515] p-3"><img src={track.albumArt} alt="" className="h-12 w-12 rounded-lg object-cover" /><div className="min-w-0"><p className="truncate text-sm font-bold">{track.name}</p><p className="truncate text-xs text-zinc-500">{track.artist} · {dateLabel(track.playedAt)}</p></div></div>)}</div></section>
    </section></main>;
}
